### ISSUE TITLE
Mix and Match Script

### ISSUE THREAD

**Issue by LiveChief** [flxn/tor-relay-configurator#14]
add a function to mix and match scripts

bridge and relay
or
exit and relay
or 
relay and bridge

**Comment by acl1704** [comment]
I don't believe it's possible off the top of my head to have a node be a normal relay and a bridge relay at the same time. Bridge relays report to the single bridge authority, whereas all other relays report to the 9dirauths.

**Comment by LiveChief** [comment]
what about a bridge and a exit 
or
bridge and relay.

**Comment by acl1704** [comment]
Bridges are different than normal relays, they perform mutually exclusive duties. I'd suggest you read some more on the functions bridges, relays, and exits serve in the Tor network.

**Comment by LiveChief** [comment]
Person > Bridge > Tor > Exit

i know but i am not very new to hosting tor and u know just sharing thoughts and trying to expand tor network.

so relay and exit?

**Comment by flxn** [comment]
A bridge is a Tor node that is not listed in the Tor directory. So if your ISP or state is filtering Tor traffic they don't know about it and you can directly connect to a bridge to circumvent the filter.
A "relay" is just a regular Tor node that receives and sends traffic from and to other nodes. They can be "guards" which means they are the entry point to the network or middle relays, that tunnel traffic from a guard to an exit.
An "exit" is the Tor node at the end of the network that connects you back to the internet.

You can't combine these roles, as acl1704 said, because they each do their own specialised thing and there are certain considerations for each of them.
